services:
  backend:
    build: ./backend
    network_mode: host
    environment:
      - ES_HOST=https://10.0.0.237:9200
      - ES_USER=elastic
      - ES_PASSWORD=changeme
      - DB_URL=postgresql://user:pass@timescaledb-svc:5432/finance
    restart: always

  frontend:
    build: ./frontend
    network_mode: host
    depends_on:
      - backend
    restart: always
